
package view;


import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.mysql.RoomDaoImpl;




public class Rooms extends javax.swing.JFrame {

    
    public Rooms() {
        dao = new RoomDaoImpl();
        initComponents();
        addTableMouseListener();
        ListaHabitaciones();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//LINEA PARA EVITAR SE CIERRE TODO EL PROGRAMA
    }
    public void ListaHabitaciones() {
         
          
       List<model.Room> Room = dao.getAll();
        DefaultTableModel model = (DefaultTableModel)tableRoom.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de cargar los nuevos datos
        for (model.Room r :  Room) {
            model.addRow(new Object[]{r.getId(),r.getnHabitacion(),r.getSimple(),r.getDoble(),r.getPrecio()});
        }
    }
    private void addTableMouseListener() {
    tableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tableRoom.getSelectedRow();
            if (row != -1) {
                roomId = Integer.parseInt(tableRoom.getValueAt(row, 0).toString());
                texHabitacionN.setText(tableRoom.getValueAt(row, 1).toString());
                jComboBoxSimple.setSelectedItem(tableRoom.getValueAt(row, 2).toString());
                jComboBoxDoble.setSelectedItem(tableRoom.getValueAt(row, 3).toString());
                texPrecio.setText(tableRoom.getValueAt(row, 4).toString());
            }
        }
    });
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    private int roomId;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texHabitacionN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSimple = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDoble = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        texPrecio = new javax.swing.JTextField();
        buttAgregar = new javax.swing.JButton();
        ButtModificar = new javax.swing.JButton();
        buttEkiminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRoom = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        jLabel2.setText("Nº de habitación");

        jLabel3.setText("Cantidad de camas");

        jLabel4.setText("Simple");

        jComboBoxSimple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        jLabel5.setText("Doble");

        jComboBoxDoble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        jLabel6.setText("Precio:");

        buttAgregar.setText("Agregar");
        buttAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAgregarActionPerformed(evt);
            }
        });

        ButtModificar.setText("Modificar");
        ButtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtModificarActionPerformed(evt);
            }
        });

        buttEkiminar.setText("Eliminar");
        buttEkiminar.setToolTipText("");
        buttEkiminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEkiminarActionPerformed(evt);
            }
        });

        tableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nº Habitación", "Simple", "Doble", "Precio"
            }
        ));
        tableRoom.setName("TableHabitacion"); // NOI18N
        jScrollPane1.setViewportView(tableRoom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDoble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(21, 21, 21)
                                .addComponent(texHabitacionN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(texPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttEkiminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(texHabitacionN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDoble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(texPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(buttAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttEkiminar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     

    private void buttAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAgregarActionPerformed
     
 try {
        int nHab = Integer.parseInt(texHabitacionN.getText());
        int sim = Integer.parseInt(jComboBoxSimple.getSelectedItem().toString());
         int dob = Integer.parseInt(jComboBoxDoble.getSelectedItem().toString());
         double prec = Double.parseDouble(texPrecio.getText());
    
          if (dao.existsByRoomNumber(nHab)) {
        // Mostrar el mensaje al usuario en la ventana actual
        JOptionPane.showMessageDialog(this, "La habitación ya existe. No se puede insertar duplicado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }      
            if (nHab == 0 || prec == 0) {
            throw new IllegalArgumentException("Todos los campos deben estar llenos.");
        }
        model.Room r = new model.Room();
   
       r.setnHabitacion(nHab);
       r.setSimple(sim);
       r.setDoble(dob);
       r.setPrecio(prec);
       
        dao.save(r);
        ListaHabitaciones();
        DefaultTableModel model = (DefaultTableModel)tableRoom.getModel();
        
       model.insertRow(0,new Object[]{r.getId(), r.getnHabitacion(),r.getSimple(),r.getDoble(),r.getPrecio()});
       ListaHabitaciones();   

          
        JOptionPane.showMessageDialog(this, "Habitación guardada exitosamente.");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    } 
        
          
    }//GEN-LAST:event_buttAgregarActionPerformed

    private void ButtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtModificarActionPerformed
      try {
      int nHab = Integer.parseInt(texHabitacionN.getText());
        int sim = Integer.parseInt(jComboBoxSimple.getSelectedItem().toString());
         int dob = Integer.parseInt(jComboBoxDoble.getSelectedItem().toString());
         double prec = Double.parseDouble(texPrecio.getText());
    
    

    model.Room r = new model.Room();
       r.setId(roomId);
       r.setnHabitacion(nHab);
       r.setSimple(sim);
       r.setDoble(dob);
       r.setPrecio(prec);

    // Actualizar el pasajero en la BD
    dao.update(r);

    // Actualizar la tabla
   ListaHabitaciones();
   // TODO add your handling code here:
      
        JOptionPane.showMessageDialog(this, "Habitación guardada exitosamente.");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_ButtModificarActionPerformed

    private void buttEkiminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEkiminarActionPerformed
     
        int selectedRow = tableRoom.getSelectedRow();
         if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una habitacion para eliminar.");
        return;
        
         
    }
         //Object id = tableRoom.getValueAt(selectedRow, 0);
         
    int id = (int) tableRoom.getValueAt(selectedRow, 0);
           model.Room r = new model.Room();
           
            r.setId(id);
            dao.delete(r);
            
              // Eliminar la fila del modelo de la tabla
         DefaultTableModel model = (DefaultTableModel) tableRoom.getModel();
         model.removeRow(selectedRow);
         
          ListaHabitaciones();
           JOptionPane.showMessageDialog(this, "Habitación eliminada exitosamente.");
    }//GEN-LAST:event_buttEkiminarActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }
    private RoomDaoImpl dao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtModificar;
    private javax.swing.JButton buttAgregar;
    private javax.swing.JButton buttEkiminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> jComboBoxDoble;
    private javax.swing.JComboBox<String> jComboBoxSimple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRoom;
    private javax.swing.JTextField texHabitacionN;
    private javax.swing.JTextField texPrecio;
    // End of variables declaration//GEN-END:variables
}
